<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{578E200D-39A1-467B-8CEA-F3632F6A010B}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>ExerciseProject</RootNamespace>
    <AssemblyName>ExerciseProject</AssemblyName>
    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AdWindows, Version=2017.11.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\Autodesk\Revit 2019\AdWindows.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIIFC">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIIFC.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIMacros">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIMacros.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIUI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUIMacros">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIUIMacros.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AutodeskDevelopmentFoundation\0504b FamilyCreat2.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0601未完ExclusionFilterw.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0603ShowSelectedElementFaceArea.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0605ShowSelectedElementFamilyName.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0604GetGeometryElementColumnFaceArea.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0602GetGeometryElementWallFaceArea.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0506FamilySymbolFilter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0505FamilySymbolFilter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0504a FamilyCreat.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0204ElementEditMoveByLocation.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0101SelectElemetById.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0102FirstSelectThenRun.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0103FirstRunThenSelect.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0104SelectElementByFilter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0105GetPropertyOfElement.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0106GetPropertyByBilutInParameter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0107ImportantPropertyAndMethod.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0108GetFmailyNameAndFamilysymbolFromFamilyinstance.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0109CreatFamilyinstanceFromFamily.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0201CreatFamilyOfExtrusion.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0202CreatFamilyTypeAndGetParameter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0203ElementEditMove.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0205ChangWallLengthByLocationCurve.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0206SetNewLocationOfColumnByChangeLocationPoint.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0207ElementEditRotate.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0208ElementEditRotateByLocationCurve.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0209ElementEditMirror.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0210ElementEditDelete.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0211DeleteElements.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0301CreatGroupAndRename.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0304CreatReferencePlaneInFamilyDocument.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0402SketchPlaneByLevelId.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0401SketchPlaneAndCreatModelCurve.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0405FilteredElementCollectorGetWall.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0406FilteredElementCollectorGetLevel.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0503ElementIsElementTypeFilter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0502ElementClassFilter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0501ElementCategoryFilter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0403CreatSketchPlanByPlane.cs" />
    <Compile Include="MyTestClass\GetNameFromElement.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0303EditFamilyAndLoadFamilyAndChangeFamilyParameter.cs" />
    <Compile Include="AutodeskDevelopmentFoundation\0302LinearArrayAndRadialArray.cs" />
    <Compile Include="Other\CmdCreatLevel.cs" />
    <Compile Include="Other\CmdTemplateTool.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="TeacherTangClass\Extensions\CreationExtension.cs" />
    <Compile Include="TeacherTangClass\Extensions\TransactionExtension.cs" />
    <Compile Include="TeacherTangClass\Extensions\XYZExtension.cs" />
    <Compile Include="TeacherTangClass\Helpers\collectorHelper.cs" />
    <Compile Include="TeacherTangClass\Helpers\DebugUtils.cs" />
    <Compile Include="TeacherTangClass\Helpers\LogHelper.cs" />
    <Compile Include="TeacherTangClass\Helpers\TransactionHelper.cs" />
  </ItemGroup>
  <ItemGroup />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>