<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{578E200D-39A1-467B-8CEA-F3632F6A010B}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>ExerciseProject</RootNamespace>
    <AssemblyName>ExerciseProject</AssemblyName>
    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AdWindows, Version=2017.11.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\Autodesk\Revit 2019\AdWindows.dll</HintPath>
    </Reference>
    <Reference Include="EPPlus">
      <HintPath>..\..\..\githubColone2\EPPlus\EPPlus\bin\Debug\EPPlus.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIIFC">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIIFC.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIMacros">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIMacros.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUIMacros">
      <HintPath>C:\Program Files\Autodesk\Revit 2019\RevitAPIUIMacros.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ClassMyTest\E1001RunSample1.cs" />
    <Compile Include="ClassMyTest\Utils.cs" />
    <Compile Include="TheCodeInBook\R0504bFamilyCreat2.cs" />
    <Compile Include="TheCodeInBook\R0601未完ExclusionFilterw.cs" />
    <Compile Include="TheCodeInBook\R0603ShowSelectedElementFaceArea.cs" />
    <Compile Include="TheCodeInBook\R0805GetCompoundStructure.cs" />
    <Compile Include="TheCodeInBook\R0902RunEpplusSample01.cs" />
    <Compile Include="TheCodeInBook\R0905WallCreat2.cs" />
    <Compile Include="TheCodeInBook\R0904WallCreat.cs" />
    <Compile Include="TheCodeInBook\R0903GetHostObjectUtils.cs" />
    <Compile Include="TheCodeInBook\R0804CreatGrid.cs" />
    <Compile Include="TheCodeInBook\R0803CreatViewByLevelId.cs" />
    <Compile Include="TheCodeInBook\R0802CreatLevel.cs" />
    <Compile Include="TheCodeInBook\R0801SetLevelBaseType.cs" />
    <Compile Include="TheCodeInBook\R0704CurveElementFilter.cs" />
    <Compile Include="TheCodeInBook\R0703ElementInstanceFilter.cs" />
    <Compile Include="TheCodeInBook\R0702ElementParameterFilter.cs" />
    <Compile Include="TheCodeInBook\R0701ElementLevelFilter.cs" />
    <Compile Include="TheCodeInBook\R0606ExclusionFilter.cs" />
    <Compile Include="TheCodeInBook\R0605ShowSelectedElementName.cs" />
    <Compile Include="TheCodeInBook\R0604GetGeometryElementColumnFaceArea.cs" />
    <Compile Include="TheCodeInBook\R0602GetGeometryElementWallFaceArea.cs" />
    <Compile Include="TheCodeInBook\R0506FamilySymbolFilter.cs" />
    <Compile Include="TheCodeInBook\R0505FamilySymbolFilter.cs" />
    <Compile Include="TheCodeInBook\R0504aFamilyCreat.cs" />
    <Compile Include="TheCodeInBook\R0204ElementEditMoveByLocation.cs" />
    <Compile Include="TheCodeInBook\R0101SelectElemetById.cs" />
    <Compile Include="TheCodeInBook\R0102FirstSelectThenRun.cs" />
    <Compile Include="TheCodeInBook\R0103FirstRunThenSelect.cs" />
    <Compile Include="TheCodeInBook\R0104SelectElementByFilter.cs" />
    <Compile Include="TheCodeInBook\R0105GetPropertyOfElement.cs" />
    <Compile Include="TheCodeInBook\R0106GetPropertyByBilutInParameter.cs" />
    <Compile Include="TheCodeInBook\R0107ImportantPropertyAndMethod.cs" />
    <Compile Include="TheCodeInBook\R0108GetFmailyNameAndFamilysymbolFromFamilyinstance.cs" />
    <Compile Include="TheCodeInBook\R0109CreatFamilyinstanceFromFamily.cs" />
    <Compile Include="TheCodeInBook\R0201CreatFamilyOfExtrusion.cs" />
    <Compile Include="TheCodeInBook\R0202CreatFamilyTypeAndGetParameter.cs" />
    <Compile Include="TheCodeInBook\R0203ElementEditMove.cs" />
    <Compile Include="TheCodeInBook\R0205ChangWallLengthByLocationCurve.cs" />
    <Compile Include="TheCodeInBook\R0206SetNewLocationOfColumnByChangeLocationPoint.cs" />
    <Compile Include="TheCodeInBook\R0207ElementEditRotate.cs" />
    <Compile Include="TheCodeInBook\R0208ElementEditRotateByLocationCurve.cs" />
    <Compile Include="TheCodeInBook\R0209ElementEditMirror.cs" />
    <Compile Include="TheCodeInBook\R0210ElementEditDelete.cs" />
    <Compile Include="TheCodeInBook\R0211DeleteElements.cs" />
    <Compile Include="TheCodeInBook\R0301CreatGroupAndRename.cs" />
    <Compile Include="TheCodeInBook\R0304CreatReferencePlaneInFamilyDocument.cs" />
    <Compile Include="TheCodeInBook\R0402SketchPlaneByLevelId.cs" />
    <Compile Include="TheCodeInBook\R0401SketchPlaneAndCreatModelCurve.cs" />
    <Compile Include="TheCodeInBook\R0405FilteredElementCollectorGetWall.cs" />
    <Compile Include="TheCodeInBook\R0406FilteredElementCollectorGetLevel.cs" />
    <Compile Include="TheCodeInBook\R0503ElementIsElementTypeFilter.cs" />
    <Compile Include="TheCodeInBook\R0502ElementClassFilter.cs" />
    <Compile Include="TheCodeInBook\R0501ElementCategoryFilter.cs" />
    <Compile Include="TheCodeInBook\R0403CreatSketchPlanByPlane.cs" />
    <Compile Include="TheCodeInBook\tem1.cs" />
    <Compile Include="ClassMyTest\GetNameFromElement.cs" />
    <Compile Include="TheCodeInBook\R0303EditFamilyAndLoadFamilyAndChangeFamilyParameter.cs" />
    <Compile Include="TheCodeInBook\R0302LinearArrayAndRadialArray.cs" />
    <Compile Include="Other\CmdCreatLevel.cs" />
    <Compile Include="Other\CmdTemplateTool.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="ClassTeacherXu\Extensions\CreationExtension.cs" />
    <Compile Include="ClassTeacherXu\Extensions\ElementIdExtension.cs" />
    <Compile Include="ClassTeacherXu\Extensions\TransactionExtension.cs" />
    <Compile Include="ClassTeacherXu\Extensions\XYZExtension.cs" />
    <Compile Include="ClassTeacherXu\Helpers\collectorHelper.cs" />
    <Compile Include="ClassTeacherXu\Helpers\DebugUtils.cs" />
    <Compile Include="ClassTeacherXu\Helpers\LogHelper.cs" />
    <Compile Include="ClassTeacherXu\Helpers\TransactionHelper.cs" />
  </ItemGroup>
  <ItemGroup />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>