using Autodesk.Revit.DB;
using System.Collections.Generic;

namespace CodeInTangsengjiewa.BinLibrary.Helpers
{
 public  static class CurveHelper
    {
        public static List<XYZ> GetPerpedicularPoint(Curve curve, XYZ po)
        {
            var result = default(List<XYZ>);
            //
            // if (curve is Arc arc)
            // {
            //     arc.ComputeDerivatives()
            // }
            // else if (curve is Ellipse)
            // {
            //
            // }
            // else if (curve is NurbSpline)
            // {
            //
            // }

            return result;
        }
    }
}